### ISSUE TITLE
Problem installing vitis 2022.2

### ISSUE THREAD

**Issue by N1ck95** [matthieu-labas/docker-petalinux#1]
I followed your steps and I downloaded the Vitis 2022.2 software in the resources/SDK folder. Then I ran the packageSDK script and I got the tgz archive. However, I keep failing the subsequent steps since the .run file is missing.
At the best of my memory I did not had such problem when installing petalinux 2019.1. Am I missing some steps with this 2022.2 version?

**Comment by matthieu-labas** [comment]
Unfortunately the script doesn't handle Vitis tools yet. It stops at 2019.1 only.

I'm planning to check it at some point but I can't guarantee when. I'm using Vitis 2022.2 now but for baremetal only so far. As soon as I need a Petalinux on it I'll probably start working again on the Docker image.

However, when you say you don't have the `.run` file, did you download the [Petalinux installer](https://www.xilinx.com/member/forms/download/xef.html?filename=petalinux-v2022.2-10141622-installer.run) from Xilinx/AMD? It's the only `petalinux-v2022.2-10141622-installer.run` file you'll need.

I just downloaded it and it seems to accept a `--skip-licence` option, which is needed for unattended install (and the point of the whole `patch-petalinux-installer.sh` script). Looking at the installer I think you *could* try and modify line `Dockerfile:103` to:

    && SKIP_LICENSE=y ./${PETALINUX_FILE}${PETALINUX_INSTALLER} --skip_licence --dir /opt/${PETALINUX_BASE} \

and no need to execute the `./patch_petalinux_installer.sh /path/to/petalinux-vXXX.X-final-installer.run` from README.

If you are able to have a working Docker image for Petalinux 2022.2, please report it here so I can add those steps.

Thanks!
